name: workshop

channels:
  - plotly
  - conda-forge
  - defaults

dependencies:

  - python=3.8.5
  - matplotlib=3.3.1
  - pandas=1.1.3
  - plotly=4.14.3
  - notebook=6.2
  - pip=20.2.3

  - pip:

    - streamlit==0.81.1
